CREATE DATABASE IF NOT EXISTS `${MARIADB_DATABASE}`;

CREATE USER IF NOT EXISTS '${MARIADB_USER}'@'%' IDENTIFIED BY '${MARIADB_PASSWORD}';
GRANT ALL ON `${MARIADB_DATABASE}`.* TO '${MARIADB_USER}'@'%';

FLUSH PRIVILEGES;

USE `${MARIADB_DATABASE}`;

CREATE TABLE IF NOT EXISTS site_config (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    value TEXT
);
